#version: '3.8'
#
#services:
#  mysql-db:
#    image: mysql:8.0
#    container_name: ecommerce-mysql
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: MYSQL
#      MYSQL_DATABASE: ecommerce
#    ports:
#      - "3310:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#  springboot-app:
#    image: ecommerce_bend:latest
#    container_name: ecommerce-app
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      MYSQL_HOST: ecommerce-mysql
#      MYSQL_PORT: 3306
#      MYSQL_DATABASE: ecommerce
#      MYSQL_PASSWORD: MYSQL
#    depends_on:
#      - mysql-db
#
#volumes:
#  mysql-data:
